# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-13 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('image', models.FileField(default='portal/static/img/default-movie.jpg', upload_to='portal/static/img/movies/<django.db.models.fields.CharField>')),
            ],
        ),
    ]
