# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-13 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='trailer',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='image',
            field=models.FileField(default='portal/static/img/default-movie.jpg', upload_to=movies.models.user_directory_path),
        ),
    ]
