# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-13 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='synopsis',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
