# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-14 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_moviereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
