# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-14 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20180614_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='movie_rating',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviereview',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
