# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-14 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20180614_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='movie_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
